# Merge a "patch branch"
name: 'Free disk space'
description: 'Free runner disk space'
runs:
  using: "composite"
  steps:
    - name: Disk usage
      shell: bash
      run: df -h
      # (as of 2023-08-23:)
      # Filesystem      Size  Used Avail Use% Mounted on
      # /dev/root        84G   62G   22G  74% /
      # tmpfs           3.4G  172K  3.4G   1% /dev/shm
      # tmpfs           1.4G  1.1M  1.4G   1% /run
      # tmpfs           5.0M     0  5.0M   0% /run/lock
      # /dev/sda15      105M  6.1M   99M   6% /boot/efi
      # /dev/sdb1        14G  4.1G  9.0G  31% /mnt
      # tmpfs           694M   12K  694M   1% /run/user/1001
    - name: Delete unneeded files
      shell: bash
      run: |
        # 2.2G	/usr/share/dotnet
        sudo rm -rf /usr/share/dotnet
        # 1.7G	/usr/share/swift
        sudo rm -rf /usr/share/swift
        # 13G	/usr/local/lib/android
        sudo rm -rf /usr/local/lib/android
        # 8.3G	/opt/hostedtoolcache/CodeQL
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        # 1.5G	/opt/hostedtoolcache/go
        sudo rm -rf /opt/hostedtoolcache/go
    - name: Disk usage
      shell: bash
      run: df -h
      # (as of 2023-08-23:)
      # Filesystem      Size  Used Avail Use% Mounted on
      # /dev/root        84G   32G   52G  39% /
      # tmpfs           3.4G  172K  3.4G   1% /dev/shm
      # tmpfs           1.4G  1.1M  1.4G   1% /run
      # tmpfs           5.0M     0  5.0M   0% /run/lock
      # /dev/sda15      105M  6.1M   99M   6% /boot/efi
      # /dev/sdb1        14G  4.1G  9.0G  31% /mnt
      # tmpfs           694M   12K  694M   1% /run/user/1001
